# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Bandaid' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bandaid

  target 'BandaidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BandaidUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
