# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Bandaid' do
  pod 'UsergridSDK', git: 'https://github.com/robertwalsh/usergrid.git', branch: 'iOS_Swift3'

end
